#ifndef INTERRUPTS_H
#define INTERRUPTS_H

#define LOAD_INTERRUPT(interrupt) set_entry((uint32_t) isr_##interrupt, interrupt); // Macro to load the interrupts on the IDT
#define DECL_ISR(n) extern void isr_##n(void); // Declare the interrupts requests. They are defined on the src/arch/isr.asm

#define LOAD_EXCEPTION(n) LOAD_INTERRUPT(n)
#define LOAD_PIC_INTERRUPT(n) LOAD_INTERRUPT(n)

#define EXCEPTIONS_LIST \
        LOAD_EXCEPTION(0) LOAD_EXCEPTION(1) LOAD_EXCEPTION(2) LOAD_EXCEPTION(3) LOAD_EXCEPTION(4) \
        LOAD_EXCEPTION(5) LOAD_EXCEPTION(6) LOAD_EXCEPTION(7) LOAD_EXCEPTION(8) LOAD_EXCEPTION(9) \
        LOAD_EXCEPTION(10) LOAD_EXCEPTION(11) LOAD_EXCEPTION(12) LOAD_EXCEPTION(13) LOAD_EXCEPTION(13) \
        LOAD_EXCEPTION(14) LOAD_EXCEPTION(15) LOAD_EXCEPTION(16) LOAD_EXCEPTION(17) LOAD_EXCEPTION(18) \
        LOAD_EXCEPTION(19) LOAD_EXCEPTION(20) LOAD_EXCEPTION(21) LOAD_EXCEPTION(22) LOAD_EXCEPTION(23) \
        LOAD_EXCEPTION(21) LOAD_EXCEPTION(22) LOAD_EXCEPTION(23) LOAD_EXCEPTION(24) LOAD_EXCEPTION(25) \
        LOAD_EXCEPTION(26) LOAD_EXCEPTION(27) LOAD_EXCEPTION(28) LOAD_EXCEPTION(29) LOAD_EXCEPTION(30)\
        LOAD_EXCEPTION(31)

#define PIC_HARDWARE_INTERRUPTS \
        LOAD_PIC_INTERRUPT(32) LOAD_PIC_INTERRUPT(33) LOAD_PIC_INTERRUPT(34) LOAD_PIC_INTERRUPT(35) \
        LOAD_PIC_INTERRUPT(36) LOAD_PIC_INTERRUPT(37) LOAD_PIC_INTERRUPT(38) LOAD_PIC_INTERRUPT(39) LOAD_PIC_INTERRUPT(40) \
        LOAD_PIC_INTERRUPT(41) LOAD_PIC_INTERRUPT(42) LOAD_PIC_INTERRUPT(43) LOAD_PIC_INTERRUPT(44) LOAD_PIC_INTERRUPT(45) \
        LOAD_PIC_INTERRUPT(46) LOAD_PIC_INTERRUPT(47)

DECL_ISR(0);
DECL_ISR(1);
DECL_ISR(2);
DECL_ISR(3);
DECL_ISR(4);
DECL_ISR(5);
DECL_ISR(6);
DECL_ISR(7);
DECL_ISR(8);
DECL_ISR(9);
DECL_ISR(10);
DECL_ISR(11);
DECL_ISR(12);
DECL_ISR(13);
DECL_ISR(14);
DECL_ISR(15);
DECL_ISR(16);
DECL_ISR(17);
DECL_ISR(18);
DECL_ISR(19);
DECL_ISR(20);
DECL_ISR(21);
DECL_ISR(22);
DECL_ISR(23);
DECL_ISR(24);
DECL_ISR(25);
DECL_ISR(26);
DECL_ISR(27);
DECL_ISR(28);
DECL_ISR(29);
DECL_ISR(30);
DECL_ISR(31);
DECL_ISR(32);
DECL_ISR(33);
DECL_ISR(34);
DECL_ISR(35);
DECL_ISR(36);
DECL_ISR(37);
DECL_ISR(38);
DECL_ISR(39);
DECL_ISR(40);
DECL_ISR(41);
DECL_ISR(42);
DECL_ISR(43);
DECL_ISR(44);
DECL_ISR(45);
DECL_ISR(46);
DECL_ISR(47);
#endif